code --install-extension aaron-bond.better-comments --force &&
code --install-extension adhamu.history-in-sublime-merge --force &&
code --install-extension adrieankhisbe.vscode-ndjson --force &&
code --install-extension aeschli.vscode-css-formatter --force &&
code --install-extension Ahmad-Na-Hddad.extension-disabler --force &&
code --install-extension albert.TabOut --force &&
code --install-extension alefragnani.project-manager --force &&
code --install-extension amazonwebservices.aws-toolkit-vscode --force &&
code --install-extension arcticicestudio.nord-visual-studio-code --force &&
code --install-extension Atishay-Jain.All-Autocomplete --force &&
code --install-extension bengreenier.vscode-node-readme --force &&
code --install-extension bierner.markdown-mermaid --force &&
code --install-extension Bruce.rona --force &&
code --install-extension christian-kohler.npm-intellisense --force &&
code --install-extension christian-kohler.path-intellisense --force &&
code --install-extension codezombiech.gitignore --force &&
code --install-extension craigb85.custom-window-zoom --force &&
code --install-extension DavidAnson.vscode-markdownlint --force &&
code --install-extension dbaeumer.vscode-eslint --force &&
code --install-extension dionmunk.vscode-notes --force &&
code --install-extension donjayamanne.githistory --force &&
code --install-extension dsznajder.es7-react-js-snippets --force &&
code --install-extension eamodio.gitlens --force &&
code --install-extension eamodio.toggle-excluded-files --force &&
code --install-extension EditorConfig.EditorConfig --force &&
code --install-extension Equinusocio.vsc-community-material-theme --force &&
code --install-extension equinusocio.vsc-material-theme-icons --force &&
code --install-extension esbenp.prettier-vscode --force &&
code --install-extension evan-buss.font-switcher --force &&
code --install-extension forbeslindesay.vscode-sql-template-literal --force &&
code --install-extension formulahendry.auto-rename-tag --force &&
code --install-extension formulahendry.code-runner --force &&
code --install-extension foxundermoon.shell-format --force &&
code --install-extension GitHub.vscode-pull-request-github --force &&
code --install-extension golang.go --force &&
code --install-extension humao.rest-client --force &&
code --install-extension jakob101.RelativePath --force &&
code --install-extension jeff-hykin.better-cpp-syntax --force &&
code --install-extension jprestidge.theme-material-theme --force &&
code --install-extension koehlma.markdown-math --force &&
code --install-extension Koihik.vscode-lua-format --force &&
code --install-extension LeetCode.vscode-leetcode --force &&
code --install-extension mdickin.markdown-shortcuts --force &&
code --install-extension mikestead.dotenv --force &&
code --install-extension ms-azuretools.vscode-docker --force &&
code --install-extension ms-dotnettools.vscode-dotnet-runtime --force &&
code --install-extension ms-python.isort --force &&
code --install-extension ms-python.python --force &&
code --install-extension ms-python.vscode-pylance --force &&
code --install-extension ms-toolsai.jupyter --force &&
code --install-extension ms-toolsai.jupyter-keymap --force &&
code --install-extension ms-toolsai.jupyter-renderers --force &&
code --install-extension ms-toolsai.vscode-jupyter-cell-tags --force &&
code --install-extension ms-toolsai.vscode-jupyter-slideshow --force &&
code --install-extension ms-vscode-remote.remote-containers --force &&
code --install-extension ms-vscode-remote.remote-ssh --force &&
code --install-extension ms-vscode-remote.remote-ssh-edit --force &&
code --install-extension ms-vscode.cpptools --force &&
code --install-extension ms-vscode.cpptools-extension-pack --force &&
code --install-extension ms-vscode.makefile-tools --force &&
code --install-extension ms-vscode.remote-explorer --force &&
code --install-extension ms-vscode.sublime-keybindings --force &&
code --install-extension myyrakle.swagger-jsdoc --force &&
code --install-extension PKief.material-icon-theme --force &&
code --install-extension redhat.vscode-yaml --force &&
code --install-extension richie5um2.vscode-sort-json --force &&
code --install-extension riyuzenn.iv --force &&
code --install-extension rust-lang.rust-analyzer --force &&
code --install-extension ryu1kn.partial-diff --force &&
code --install-extension sainnhe.gruvbox-material --force &&
code --install-extension serayuzgur.crates --force &&
code --install-extension shakram02.bash-beautify --force &&
code --install-extension sldobri.nord-5-stars --force &&
code --install-extension sumneko.lua --force &&
code --install-extension Swellaby.rust-pack --force &&
code --install-extension teabyii.ayu --force &&
code --install-extension tgreen7.vs-code-node-require --force &&
code --install-extension timonwong.shellcheck --force &&
code --install-extension tushortz.python-extended-snippets --force &&
code --install-extension usernamehw.errorlens --force &&
code --install-extension viktorqvarfordt.vscode-pitch-black-theme --force &&
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples --force &&
code --install-extension VisualStudioExptTeam.vscodeintellicode --force &&
code --install-extension WallabyJs.quokka-vscode --force &&
code --install-extension wraith13.zoombar-vscode --force &&
code --install-extension wwm.better-align --force &&
code --install-extension xabikos.JavaScriptSnippets --force &&
code --install-extension yzhang.markdown-all-in-one --force
